### ISSUE TITLE
What bf variant to use?

### ISSUE THREAD

**Issue by Zabolekar** [lestrozi/pipevm#5]
Hi,

can you please document (or point to the relevant part of the documentation) how to run `sh.bf`? I'd like to use it for testing my own bf compiler. In particular, I'd like to know:

- the required cell size, signedness, and behaviour on overflow and underflow
- the memory requirements and whether something specific should happen if the code oversteps tape boundaries
- how `,` should handle EOF

Thank you in advance.

**Comment by lestrozi** [comment]
Sorry for the long wait!

I tested this on unsigned 8 bit cells with overflows; not sure about memory requirements, but I assume 2 KBs should be enough.
EOF is returned as 0x00. This is not ideal, but this is mostly a prototype, so I didn't bother dealing with it in the filesystem module. Some modules (such as Text) has a SPECIAL_CHAR=0xff which can be used to encode every possible char (0xff is encoded as 0xff+0xff while 0x00 could be encoded as 0xff+0x00).

**Comment by Zabolekar** [comment]
I see. My compiler uses the same cell format and treats EOF as 0 as well, so I gave it a try. The compiled function accepts input, but there is no prompt and no output. Might be a bug in my compiler, will investigate further, but probably not today. Thanks for the example :)

**Comment by Zabolekar** [comment]
I've looked into it and found some possible buffering issues in my implementation, but I don't think I really understand what `sh.bf` does. At the very beginning, for example, it fills the tape with [0 0 255 128 1 10 32 36 1 0 0 0 0 0 1], of which the 0 255 128 1 10 32 36 part is in the comments. Then it goes to the beginning and outputs the characters 255 128 10 36 32. I see that 10 36 32 is '\n$ ', which makes sense. But why 255 128?

**Comment by lestrozi** [comment]
Those are "control codes" to select a device: https://github.com/lestrozi/pipevm/blob/main/pipevm.py#L79
255 means "I'm sending a command", 128 means "select device 0" (text.Text). You shouldn't need to worry about that though; this is internal implementation of the pipevm, so as long as you pipe this to pipevm.py, you'll see "\n $" in the "virtual screen".

**Comment by Zabolekar** [comment]
Thank you for the explanation, it makes sense to me now.
